name: Eventia CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      ENV: TEST   # <<<<<< EVITA CONEXIÓN A MYSQL DURANTE TESTS

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar pruebas unitarias
      run: |
        pytest eventia//unit --maxfail=1 --disable-warnings

    - name: Ejecutar pruebas de integración
      run: |
        pytest eventia/test/integration --maxfail=1 --disable-warnings

    - name: Análisis estático de seguridad (Bandit)
      run: |
        pip install bandit
        bandit -r app

    - name: Pruebas de sistema (opcional)
      if: always()
      run: |
        if [ -d "eventia/test/system" ]; then
          pytest eventia/test/system
        else
          echo "No hay pruebas de sistema."
        fi

    - name: Todo correcto
      if: success()
      run: echo "OK"

    - name: Algo falló
      if: failure()
      run: echo "Pipeline FAILED"

